# Generated by Django 4.2.7 on 2026-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidates/resumes/%Y/%m/')),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('portfolio_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('education_level', models.CharField(blank=True, db_index=True, max_length=50)),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('raw_cv_text', models.TextField(blank=True, help_text='Texte extrait du CV pour recherche')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='companies.company')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'db_table': 'candidates_candidate',
                'indexes': [models.Index(fields=['company', 'email'], name='candidates__company_737faf_idx'), models.Index(fields=['company', 'deleted_at'], name='candidates__company_92351c_idx'), models.Index(fields=['country', 'experience_years'], name='candidates__country_30a30d_idx')],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
