# Generated by Django 4.2.7 on 2026-02-24 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='[{"degree":"","institution":"","year":""}]'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.JSONField(blank=True, default=list, help_text='[{"title":"","company":"","start_date":"","end_date":"","description":""}]'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='[{"language":"","level":""}]'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='[{"name":"","contact":""}]'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Compte candidat (si inscrit sur la plateforme).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
