# Generated by Django 4.2.7 on 2026-02-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_user_and_extended_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.CharField(blank=True, help_text='Current address', max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cell_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city_province',
            field=models.CharField(blank=True, help_text='City or Province (dropdown)', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, help_text='Mr, Mrs, Ms, etc.', max_length=20),
        ),
    ]
