# Generated by Django 4.2.7 on 2026-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_add_personal_details_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='city_province',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, help_text='Civilité: Mr, Mrs, Ms, Dr', max_length=20),
        ),
    ]
