# Generated by Django 5.0.14 on 2026-02-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_add_personal_details_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='Liste de formations: education_type, degree_type, discipline, other_specializations, country, institution, city_campus, study_level, enrollment_status, start_year, end_year'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.JSONField(blank=True, default=list, help_text='Liste d’expériences: employment_status, employment_type, job_title, job_contract_type, responsibilities, start_month, start_year, company_name, company_sector, country, city, department, manager_name, etc.'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Liste de langues: language, speaking_proficiency, reading_proficiency, writing_proficiency (e.g. fluent, proficient, intermediate, basic, elementary)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='Liste de références: first_name, last_name, organization, job_title, phone, email'),
        ),
    ]
