# Generated by Django 4.2.7 on 2026-06-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_p10_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidate',
            new_name='candidates__company_e294fa_idx',
            old_name='cand_company_anon_idx',
        ),
        migrations.RenameIndex(
            model_name='candidate',
            new_name='candidates__company_728ba1_idx',
            old_name='cand_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='candidate',
            new_name='candidates__company_80d1ef_idx',
            old_name='cand_company_updated_idx',
        ),
    ]
