# Generated by Django 4.2.7 on 2026-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('internship', 'Stage'), ('part_time', 'Temps partiel'), ('other', 'Autre')], db_index=True, default='cdi', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('closed', 'Clôturée'), ('archived', 'Archivée')], db_index=True, default='draft', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, default='XOF', max_length=3)),
                ('salary_visible', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='companies.company')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'db_table': 'jobs_joboffer',
            },
        ),
        migrations.CreateModel(
            name='ScreeningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('keywords', 'Mots-clés (CV)'), ('min_experience', "Années d'expérience min"), ('education_level', "Niveau d'études"), ('location', 'Localisation'), ('custom', 'Personnalisé')], db_index=True, max_length=30)),
                ('value', models.JSONField(default=dict, help_text='Ex: {"keywords": ["Python", "Django"]}, {"years": 3}, {"level": "master"}')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Pondération pour le scoring (ex: 1.5 = règle prioritaire)', max_digits=4)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_rules', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Règle de screening',
                'verbose_name_plural': 'Règles de screening',
                'db_table': 'jobs_screeningrule',
                'ordering': ['order', 'id'],
            },
        ),
    ]
