# Generated by Django 4.2.7 on 2026-02-24 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='screeningrule',
            index=models.Index(fields=['job_offer', 'order'], name='jobs_screen_job_off_89e30b_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['company', 'status'], name='jobs_joboff_company_29bbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['status', 'published_at'], name='jobs_joboff_status_1dc1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['country', 'status'], name='jobs_joboff_country_13296a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joboffer',
            unique_together={('company', 'slug')},
        ),
    ]
