# Generated by Django 4.2.7 on 2026-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='description_document',
            field=models.FileField(blank=True, help_text='PDF ou Word : fiche offre à afficher aux candidats. Si présent, la description texte est optionnelle.', null=True, upload_to='jobs/documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True, help_text='Optionnel si un document est joint.'),
        ),
    ]
