# Generated by Django 4.2.7 on 2026-02-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_description_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='description_document',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(),
        ),
    ]
