# Generated by Django 4.2.7 on 2026-02-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_selectionsettings_scoring_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningrule',
            name='rule_type',
            field=models.CharField(choices=[('keywords', 'Mots-clés (CV)'), ('skills', 'Compétences'), ('language', 'Langue'), ('min_experience', "Années d'expérience min"), ('education_level', "Niveau d'études"), ('location', 'Localisation'), ('custom', 'Personnalisé')], db_index=True, max_length=30),
        ),
    ]
