# Generated by Django 5.0.14 on 2026-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_add_skills_language_rule_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningrule',
            name='rule_type',
            field=models.CharField(choices=[('keywords', 'Mots-clés (CV)'), ('min_experience', "Années d'expérience min"), ('education_level', "Niveau d'études"), ('location', 'Localisation'), ('custom', 'Personnalisé')], db_index=True, max_length=30),
        ),
    ]
