# Generated by Django 4.2.7 on 2026-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('recruiter', 'Recruiter'), ('candidate', 'Candidat')], db_index=True, default='recruiter', max_length=20),
        ),
    ]
