# Generated by Django 4.2.7 on 2026-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('applied', 'Postulé'), ('preselected', 'Pré-sélectionné'), ('shortlisted', 'Shortlisté'), ('interview', 'En entretien'), ('offer', 'Offre envoyée'), ('hired', 'Embauché'), ('rejected', 'Refusé'), ('withdrawn', 'Retirée')], db_index=True, default='applied', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('screening_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score de matching avec les règles de screening', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'db_table': 'applications_application',
            },
        ),
    ]
