# Generated by Django 4.2.7 on 2026-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_offer', 'status'], name='application_job_off_7d1a59_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'status'], name='application_candida_a79be7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'applied_at'], name='application_status_89c2ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job_offer', 'candidate')},
        ),
    ]
