# Generated by Django 4.2.7 on 2026-02-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/cover_letters/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='application',
            name='signature_text',
            field=models.CharField(blank=True, help_text='Signature électronique : Prénom Nom ou email', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
