# Generated by Django 4.2.7 on 2026-02-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_ats_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='preselection_score_details',
            field=models.JSONField(blank=True, help_text='Détail par critère (scoring pondéré) pour transparence RH', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='selection_score_details',
            field=models.JSONField(blank=True, help_text='Détail par critère (scoring pondéré) pour transparence RH', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='screening_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score de matching avec les règles de screening (legacy, voir preselection_score)', max_digits=5, null=True),
        ),
    ]
