# Generated by Django 4.2.7 on 2026-02-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_scoring_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='preselection_score_details',
            field=models.JSONField(blank=True, help_text='Détail par critère (criterion, passed, weight_awarded) pour transparence RH', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='selection_score_details',
            field=models.JSONField(blank=True, help_text='Détail par critère (criterion, passed, weight_awarded) pour transparence RH', null=True),
        ),
        migrations.CreateModel(
            name='MLScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_version', models.CharField(db_index=True, help_text='Version du modèle utilisé (ex: v1.0.0, 20250226-stub)', max_length=64)),
                ('predicted_score', models.FloatField(help_text='Score prédit par le modèle (0–100)')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confiance du modèle (0–1), optionnel', null=True)),
                ('features_json', models.JSONField(blank=True, default=dict, help_text='Features utilisées pour la prédiction (feature store)')),
                ('ml_explanation_json', models.JSONField(blank=True, help_text='Explications IA (SHAP, feature importance, etc.) pour interprétabilité future', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_scores', to='applications.application')),
            ],
            options={
                'verbose_name': 'Score ML',
                'verbose_name_plural': 'Scores ML',
                'db_table': 'applications_mlscore',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'created_at'], name='application_applica_c24699_idx'), models.Index(fields=['model_version', 'created_at'], name='application_model_v_770773_idx')],
            },
        ),
    ]
