# Generated by Django 4.2.7 on 2026-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_p10_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationauditlog',
            new_name='application_applica_9da4c7_idx',
            old_name='applications_audit_app_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationauditlog',
            new_name='application_action_e04e5b_idx',
            old_name='applications_audit_act_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationauditlog',
            new_name='application_actor_i_393c02_idx',
            old_name='applications_audit_actor_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationnote',
            new_name='application_applica_3131d8_idx',
            old_name='applications_note_app_ts_idx',
        ),
        migrations.AlterField(
            model_name='applicationauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicationnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
