# Generated by Django 4.2.7 on 2026-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('test_type', models.CharField(choices=[('technical', 'Technique'), ('personality', 'Personnalité'), ('language', 'Langue'), ('case_study', 'Étude de cas'), ('other', 'Autre')], db_index=True, default='technical', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score minimum pour valider (ex: 60.00)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='companies.company')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'db_table': 'tests_test',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiples'), ('text', 'Texte libre'), ('number', 'Numérique'), ('boolean', 'Oui/Non')], db_index=True, max_length=20)),
                ('text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, help_text='Pour single/multiple: [{"id": "a", "label": "Option A", "correct": true}]')),
                ('correct_answer', models.JSONField(blank=True, help_text="Réponse attendue (texte, nombre, ou liste d'ids pour QCM)", null=True)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'tests_question',
                'ordering': ['test', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('submitted', 'Soumis'), ('scored', 'Noté'), ('expired', 'Expiré')], db_index=True, default='pending', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Réponses: { "question_id": "answer" ou ["id1", "id2"] }')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='applications.application')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='tests.test')),
            ],
            options={
                'verbose_name': 'Résultat de test candidat',
                'verbose_name_plural': 'Résultats de tests candidats',
                'db_table': 'tests_candidatetestresult',
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['company', 'is_active'], name='tests_test_company_0a0238_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'order'], name='tests_quest_test_id_983ded_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatetestresult',
            index=models.Index(fields=['application', 'status'], name='tests_candi_applica_5eb7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatetestresult',
            index=models.Index(fields=['test', 'status'], name='tests_candi_test_id_fc19dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatetestresult',
            unique_together={('application', 'test')},
        ),
    ]
