# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_score',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Score total (somme des points des questions), recalculé automatiquement.',
                max_digits=6,
                null=True,
            ),
        ),
    ]
