# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.test')),
            ],
            options={
                'verbose_name': 'Section de test',
                'verbose_name_plural': 'Sections de test',
                'db_table': 'tests_section',
                'ordering': ['test', 'order', 'id'],
                'indexes': [
                    models.Index(fields=['test', 'order'], name='tests_sec_test_ord_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.section', db_index=True),
        ),
        migrations.AddField(
            model_name='question',
            name='section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='competencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tests/questions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='question',
            name='code_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'order'], name='tests_quest_sec_ord_idx'),
        ),
    ]
