# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_section_question_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.JSONField(blank=True, help_text='Réponse brute du candidat pour cette question (texte, JSON, code, méta fichier).', null=True)),
                ('score_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Score obtenu pour cette question (0 à points).', max_digits=6, null=True)),
                ('file', models.FileField(blank=True, help_text='Fichier réponse (Excel, Word, PDF, PowerPoint, PBIX, etc.) pour les questions file_upload.', null=True, upload_to='tests/answers/%Y/%m/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_rows', to='tests.candidatetestresult', db_index=True)),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses à des questions',
                'db_table': 'tests_answer',
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['session', 'question'], name='tests_answ_session_idx'),
        ),
    ]
