# Generated by Django 5.0.14 on 2026-03-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_ml_score_model'),
        ('companies', '0001_initial'),
        ('jobs', '0009_alter_screeningrule_rule_type'),
        ('tests', '0004_answer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='answer',
            new_name='tests_answe_session_4e0a1c_idx',
            old_name='tests_answ_session_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='tests_quest_section_bc8e95_idx',
            old_name='tests_quest_sec_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='section',
            new_name='tests_secti_test_id_668451_idx',
            old_name='tests_sec_test_ord_idx',
        ),
        migrations.AddField(
            model_name='candidatetestresult',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Adresse IP vue lors de la session de test (pour audit).', null=True),
        ),
        migrations.AddField(
            model_name='candidatetestresult',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='Test terminé (soumis ou expiré).'),
        ),
        migrations.AddField(
            model_name='candidatetestresult',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='Marqué comme suspect si tab_switch_count dépasse le seuil.'),
        ),
        migrations.AddField(
            model_name='candidatetestresult',
            name='tab_switch_count',
            field=models.PositiveSmallIntegerField(default=0, help_text="Nombre de changements d'onglet détectés côté client pendant le test."),
        ),
        migrations.AddField(
            model_name='test',
            name='access_code',
            field=models.CharField(blank=True, help_text="Code d'accès (token partagé) pour les candidats shortlistés de l'offre liée.", max_length=32),
        ),
        migrations.AddField(
            model_name='test',
            name='job_offer',
            field=models.ForeignKey(blank=True, help_text="Offre concernée par ce test (pour restreindre l'accès aux candidats shortlistés).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='jobs.joboffer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, help_text='Fichier ressource (énoncé détaillé, jeu de données, template, etc.).', null=True, upload_to='tests/questions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_language',
            field=models.CharField(blank=True, help_text='Langage attendu pour une question de type code (ex: python, javascript).', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='competencies',
            field=models.JSONField(blank=True, default=list, help_text='Tags de compétences, ex: ["Python", "Django"] pour scoring par compétence.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Pour QCM: [{"id": "a", "label": "Option A", "correct": true}]'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, help_text='Poids / score maximum pour la question.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('qcm_single', 'QCM (choix unique)'), ('qcm_multi', 'QCM (choix multiples)'), ('true_false', 'Vrai / Faux'), ('numeric', 'Numérique'), ('open_text', 'Texte libre'), ('file_upload', 'Upload de fichier'), ('code', 'Question de code'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiples'), ('text', 'Texte libre'), ('number', 'Numérique'), ('boolean', 'Oui/Non')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='section_title',
            field=models.CharField(blank=True, help_text='Nom de section (fallback si section FK non utilisée).', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Code de départ facultatif pour les questions de code.'),
        ),
        migrations.AddIndex(
            model_name='candidatetestresult',
            index=models.Index(fields=['is_flagged'], name='tests_candi_is_flag_c7ec95_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['job_offer', 'is_active'], name='tests_test_job_off_d4a9ff_idx'),
        ),
    ]
