# Generated by Django 4.2.7 on 2026-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_anonymize_uploads'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='answer',
            new_name='tests_answe_pending_b289a6_idx',
            old_name='tests_answe_pend_rev_idx',
        ),
        migrations.RenameIndex(
            model_name='candidatetestresult',
            new_name='tests_candi_is_pass_053d0e_idx',
            old_name='tests_candi_is_pass_idx',
        ),
        migrations.RenameIndex(
            model_name='correctorassignment',
            new_name='tests_corre_token_f8118e_idx',
            old_name='tests_corr_token_rvk_idx',
        ),
        migrations.RenameIndex(
            model_name='correctorassignment',
            new_name='tests_corre_test_id_be317c_idx',
            old_name='tests_corr_test_rvk_idx',
        ),
        migrations.RenameIndex(
            model_name='correctorassignment',
            new_name='tests_corre_company_591164_idx',
            old_name='tests_corr_co_rvk_idx',
        ),
        migrations.RenameIndex(
            model_name='testaccessgrant',
            new_name='tests_testa_token_89cd9e_idx',
            old_name='tests_grant_token_rvk_idx',
        ),
        migrations.RenameIndex(
            model_name='testaccessgrant',
            new_name='tests_testa_applica_59e53a_idx',
            old_name='tests_grant_app_rvk_idx',
        ),
        migrations.RenameIndex(
            model_name='testauditlog',
            new_name='tests_testa_session_b7d39c_idx',
            old_name='tests_audit_sess_act_idx',
        ),
        migrations.RenameIndex(
            model_name='testauditlog',
            new_name='tests_testa_actor_i_8a290a_idx',
            old_name='tests_audit_actor_idx',
        ),
        migrations.RenameIndex(
            model_name='testauditlog',
            new_name='tests_testa_correct_c7605c_idx',
            old_name='tests_audit_corr_idx',
        ),
        migrations.AlterField(
            model_name='test',
            name='access_code',
            field=models.CharField(blank=True, help_text="Code d'accès (token partagé) pour les candidats shortlistés de l'offre liée. P5 : préférer TestAccessGrant.token (un token unique par candidat).", max_length=32),
        ),
    ]
