# Generated by Django 4.2.7 on 2026-02-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('template_type', models.CharField(choices=[('application_received', 'Candidature reçue'), ('application_rejected', 'Candidature refusée'), ('shortlist_notification', 'Notification shortlist'), ('interview_invitation', 'Invitation entretien'), ('offer_letter', "Lettre d'offre"), ('test_invitation', 'Invitation test'), ('reminder', 'Relance'), ('custom', 'Personnalisé')], db_index=True, default='custom', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='HTML avec variables: {{ candidate_name }}, {{ job_title }}, etc.')),
                ('body_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='companies.company')),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'emails",
                'db_table': 'emails_emailtemplate',
                'indexes': [models.Index(fields=['company', 'is_active'], name='emails_emai_company_550d21_idx')],
                'unique_together': {('company', 'template_type')},
            },
        ),
    ]
