# Generated by Django 4.2.7 on 2026-02-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(blank=True, default='', help_text='HTML avec variables: {{ candidate_name }}, {{ job_title }}, etc.'),
        ),
    ]
