# Generated by Django 4.2.7 on 2026-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emaillog_and_template_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_company_e54da5_idx',
            old_name='emails_emai_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_templat_846c55_idx',
            old_name='emails_emai_tplstatus_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_recipie_fd7f9f_idx',
            old_name='emails_emai_recipient_dt_idx',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='backend utilisé (ex. "brevo_api", "smtp", "console").', max_length=40),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identifiant retourné par Brevo (header X-Message-Id).', max_length=255),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='related_application_id',
            field=models.IntegerField(blank=True, db_index=True, help_text="ID de l'Application liée (sans FK pour éviter les cycles).", null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='related_object_id',
            field=models.IntegerField(blank=True, db_index=True, help_text="ID de l'objet déclencheur (assignment, grant, etc.).", null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='related_object_type',
            field=models.CharField(blank=True, default='', help_text='Type de l\'objet déclencheur (ex. "CorrectorAssignment").', max_length=80),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='template_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Type d'email (correspond à EmailTemplate.TemplateType).", max_length=40),
        ),
    ]
